export interface Card {
  artist: string
  borderColor: string
  colorIdentity: string
  colorIndicator: string
  colors: string
  convertedManaCost: number
  edhrecRank: number
  faceConvertedManaCost: number
  flavorText: string
  hasFoil: boolean
  hasNonFoil: boolean
  isAlternative: boolean
  isArena: boolean
  isFullArt: boolean
  isMtgo: boolean
  isOnlineOnly: boolean
  isOversized: boolean
  isPaper: boolean
  isPromo: boolean
  isReprint: boolean
  isReserved: boolean
  isStarter: boolean
  isStorySpotlight: boolean
  isTextless: boolean
  layout: string
  leadershipSkills: string
  legalities: string
  loyalty: string
  manaCost: string
  mcmId: number
  mcmMetaId: number
  mtgArenaId: number
  mtgoFoilId: number
  mtgoId: number
  multiverseId: number
  name: string
  names: string
  number: string
  originalText: string
  originalType: string
  otherFaceIds: string
  power: string
  prices: string
  printings: string
  rarity: string
  reverseRelated: string
  rulings: string
  scryfallId: string
  scryfallOracleId: string
  scryfallIllustrationId: string
  side: string
  subtypes: string
  supertypes: string
  tcgplayerProductId: number
  text: string
  toughness: string
  cardType: string
  cardTypes: string
  uuid: string
  variations: string
  watermark: string
  asciiName: string
  flavorName: string
}
